name: CI/CD for COCONUT Bluebook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Clean cache and build
      - name: Clean cache and build
        run: |
          rm -rf .cache build
          
      # Build with Antora
      - name: Build with Antora
        run: |
          docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora --cache-dir=./.cache --stacktrace antora-playbook.yml

      # Debug build directory
      - name: Debug build directory
        run: |
          echo "Checking build directory in runner"
          ls -l build
          ls -l build/bluebook

      # Setup SSH key for rsync
      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "Host ${{ secrets.VPS_HOST }}" >> ~/.ssh/config
          echo "  User ${{ secrets.VPS_USERNAME }}" >> ~/.ssh/config
          echo "  Port ${{ secrets.VPS_SSH_PORT }}" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          cat ~/.ssh/config

      # Prepare VPS directory
      - name: Prepare VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Preparing directory"
            rm -rf /home/gusdur/bluebook/build
            mkdir -p /home/gusdur/bluebook

      # Upload build using rsync
      - name: Upload build to VPS via rsync
        run: |
          rsync -avz --delete --progress \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./build/ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/home/gusdur/bluebook/build/

      # Move to web directory
      - name: Move build to web directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Moving build to /var/www/html"
            rm -rf /var/www/html/*
            cp -r /home/gusdur/bluebook/build/* /var/www/html/
            chmod -R 755 /var/www/html
            ls -la /var/www/html

      # Finalize deployment
      - name: Finalize deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Final checks"
            ls -l /var/www/html
            echo "Deployment completed"
