name: CI/CD for COCONUT Bluebook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Checkout repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup SSH Agent dengan key dari secrets
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Test koneksi SSH sebelum deploy
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.VPS_SSH_PORT }} \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
              "echo '✅ SSH Connection Successful!'"

      # Bersihkan cache dan build
      - name: Clean workspace
        run: |
          rm -rf .cache build

      # Build dengan Antora
      - name: Build with Antora
        run: |
          docker run -u $(id -u) \
                 -v $PWD:/antora:Z \
                 --rm -t antora/antora \
                 --cache-dir=./.cache \
                 --stacktrace \
                 draft/antona-playbook.yml

      # Verifikasi hasil build
      - name: Verify build output
        run: |
          echo "Build contents:"
          ls -l build/site/
          [ -f build/site/index.html ] || exit 1

      # Deploy ke VPS
      - name: Deploy to Production
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "🔄 Starting Deployment..."
            sudo rm -rf /var/www/html/build
            sudo mkdir -p /var/www/html/build
            echo "📁 Directory cleaned"

      - name: Upload files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "build/site/*"
          target: "/var/www/html/build"
          strip_components: 2
          overwrite: true

      # Final setup dan restart nginx
      - name: Finalize Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "🔧 Setting permissions..."
            sudo chown -R www-data:www-data /var/www/html/build
            sudo chmod -R 755 /var/www/html/build
            
            echo "🔍 Verifying nginx config..."
            sudo nginx -t && sudo systemctl restart nginx
            
            echo "🚀 Deployment Successful!"
            echo "🌐 Available at: http://${{ secrets.VPS_HOST }}/build"
