
name: CI/CD for COCONUT Bluebook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # Checkout repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Bersihkan cache dan build
      - name: Clean workspace
        run: |
          rm -rf .cache build
      # Build dengan Antora
      - name: Build with Antora
        run: |
          docker run -u $(id -u) \
                 -v $PWD:/antora:Z \
                 --rm -t antora/antora:3.1.2 \
                 --cache-dir=./.cache \
                 --stacktrace \
                 antora-playbook.yml
      # Validasi hasil build
      - name: Validate build output
        run: |
          echo "Build structure:"
          ls -lR build/
          
          if [ -f "build/index.html" ] && [ -d "build/bluebook/draft" ]; then
            echo "✅ Build validation passed"
          else
            echo "❌ Error: Invalid build structure"
            exit 1
          fi
      # Simpan build sebagai artefak
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: bluebook-build
          path: build/
          retention-days: 1

      # Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Test koneksi SSH
      - name: Test SSH connection
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.VPS_SSH_PORT }} \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
              "echo 'SSH connection successful'"
      # Deploy menggunakan Rsync (VERSI DIPERBAIKI)
      - name: Deploy with Rsync
        run: |
          echo "Installing rsync..."
          sudo apt-get update && sudo apt-get install -y rsync
          
          echo "Syncing build directory..."
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.VPS_SSH_PORT }} -o StrictHostKeyChecking=no" \
            build/ \
            ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/home/gusdur/bluebook-coconut/build/
          
          echo "Verifying transfer..."
          ssh -p ${{ secrets.VPS_SSH_PORT }} \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
              "ls -l /home/gusdur/bluebook-coconut/build/bluebook/draft/"
      # Final deployment steps
      - name: Finalize deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Moving to production..."
            rm -rf /var/www/html/build
            cp -r /home/gusdur/bluebook-coconut/build /var/www/html/
            
            echo "Setting permissions..."
            chmod -R 755 /var/www/html/build
            ls -la /var/www/html/build
                      
            echo "Validating deployment..."
            if [ -f "/var/www/html/build/bluebook/draft/coconut-draft-inesa.html" ]; then
              echo "✅ Deployment successful"
              echo "🌐 Access at: http://${{ secrets.VPS_HOST }}/build"
            else
              echo "❌ Deployment failed - missing critical files"
              exit 1
            fi
            
            echo "Restarting nginx..."
