name: CI/CD for COCONUT Bluebook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Bersihkan cache dan build
      - name: Clean cache and build
        run: |
          rm -rf .cache build

      # Build dengan Antora
      - name: Build with Antora
        run: |
          docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora --cache-dir=./.cache --stacktrace antora-playbook.yml

      # Debug direktori build
      - name: Debug build directory
        run: |
          echo "Checking build directory in runner"
          ls -lR build
          if [ -d "build/bluebook" ]; then echo "Subdirectory build/bluebook exists"; fi
          if [ -d "build/bluebook/draft" ]; then echo "Subdirectory build/bluebook/draft exists"; fi
          find build -type f -name "*.html"

      # Validasi struktur build
      - name: Validate build structure
        run: |
          echo "Validating expected files"
          if [ -f "build/index.html" ] && [ -f "build/404.html" ] && [ -d "build/bluebook/draft" ]; then
            echo "Build structure is valid (bluebook/draft)"
          elif [ -f "build/index.html" ] && [ -f "build/404.html" ] && [ -d "build/draft" ]; then
            echo "Build structure is valid (draft)"
          else
            echo "Error: Expected build structure not found"
            ls -lR build
            exit 1
          fi

      # Simpan build sebagai artefak
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bluebook-build
          path: build/
          retention-days: 1

      # Debug secrets
      - name: Debug secrets
        run: |
          echo "VPS_HOST is set: ${{ secrets.VPS_HOST != '' }}"
          echo "VPS_USERNAME is set: ${{ secrets.VPS_USERNAME != '' }}"
          echo "VPS_SSH_KEY is set: ${{ secrets.VPS_SSH_KEY != '' }}"
          echo "VPS_SSH_PORT is set: ${{ secrets.VPS_SSH_PORT != '' }}"

      # Tes konektivitas SSH
      - name: Test SSH connectivity
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            whoami
            hostname
            netstat -tuln | grep :${{ secrets.VPS_SSH_PORT }}

      # Persiapkan direktori di VPS
      - name: Prepare VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Preparing temporary directory"
            rm -rf /home/gusdur/bluebook-coconut/build
            mkdir -p /home/gusdur/bluebook-coconut/build
            chmod 755 /home/gusdur/bluebook-coconut/build

      # Unduh artefak dan kompres build
      - name: Download and compress build
        run: |
          echo "Downloading build artifact"
          mkdir -p build
          echo "Compressing build to tarball"
          if [ -d "build/bluebook" ]; then
            tar -czf bluebook-build.tar.gz -C build/bluebook .
          else
            tar -czf bluebook-build.tar.gz -C build .
          fi
          ls -lh bluebook-build.tar.gz

      # Unduh artefak (sebelumnya diunggah)
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: bluebook-build
          path: build/

      # Unggah tarball ke VPS
      - name: Upload tarball to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Uploading tarball to VPS"
            scp /github/workspace/bluebook-build.tar.gz gusdur@${{ secrets.VPS_HOST }}:/home/gusdur/bluebook-coconut/bluebook-build.tar.gz
            echo "Extracting tarball on VPS"
            tar -xzf /home/gusdur/bluebook-coconut/bluebook-build.tar.gz -C /home/gusdur/bluebook-coconut/build/
            rm /home/gusdur/bluebook-coconut/bluebook-build.tar.gz
            ls -l /home/gusdur/bluebook-coconut/build

      # Pindahkan build ke direktori tujuan
      - name: Move build to web directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Moving build to /var/www/html/build"
            rm -rf /var/www/html/build
            mv /home/gusdur/bluebook-coconut/build /var/www/html/build
            chmod -R 755 /var/www/html/build
            ls -la /var/www/html/build

      # Finalisasi deployment
      - name: Finalize deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Finalizing deployment"
            ls -l /var/www/html/build
            echo "Deployment completed"
