name: CI/CD for COCONUT Bluebook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Bersihkan cache dan build
      - name: Clean cache and build
        run: |
          rm -rf .cache build

      # Build dengan Antora
      - name: Build with Antora
        run: |
          docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora --cache-dir=./.cache --stacktrace antora-playbook.yml

      # Debug direktori build
      - name: Debug build directory
        run: |
          echo "Checking build directory in runner"
          ls -lR build
          if [ -d "build/bluebook" ]; then echo "Subdirectory build/bluebook exists"; fi

      # Simpan build sebagai artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bluebook-build
          path: build/
          retention-days: 1

      # Debug secrets
      - name: Debug secrets
        run: |
          echo "VPS_HOST is set: ${{ secrets.VPS_HOST != '' }}"
          echo "VPS_USERNAME is set: ${{ secrets.VPS_USERNAME != '' }}"
          echo "VPS_SSH_KEY is set: ${{ secrets.VPS_SSH_KEY != '' }}"
          echo "VPS_SSH_PORT is set: ${{ secrets.VPS_SSH_PORT != '' }}"

      # Tes konektivitas SSH
      - name: Test SSH connectivity
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            whoami
            hostname
            netstat -tuln | grep :${{ secrets.VPS_SSH_PORT }}

      # Persiapkan direktori di VPS
      - name: Prepare VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Preparing temporary directory"
            rm -rf /home/gusdur/bluebook-coconut/build
            mkdir -p /home/gusdur/bluebook-coconut/build
            chmod 755 /home/gusdur/bluebook-coconut/build

      # Transfer build ke VPS dengan tarball streaming
      - name: Transfer build to VPS
        run: |
          tar -C build -czf - . | ssh -o StrictHostKeyChecking=no -p ${{ secrets.VPS_SSH_PORT }} ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} "tar -C /home/gusdur/bluebook-coconut/build -xzf -"

      # Normalisasi struktur dan deploy
      - name: Deploy to web directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Normalizing build structure"
            rm -rf /var/www/html/build
            mkdir -p /var/www/html/build
            if [ -d "/home/gusdur/bluebook-coconut/build/bluebook" ]; then
              mv /home/gusdur/bluebook-coconut/build/bluebook/* /var/www/html/build/
            else
              mv /home/gusdur/bluebook-coconut/build/* /var/www/html/build/
            fi
            chmod -R 755 /var/www/html/build
            chown -R www-data:www-data /var/www/html/build
            ls -la /var/www/html/build
            rm -rf /home/gusdur/bluebook-coconut/build
            echo "Deployment completed"
