name: CI/CD for COCONUT Bluebook

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean cache and build
        run: |
          rm -rf .cache build

      - name: Build with Antora
        run: |
          docker run -u $(id -u) -v $PWD:/antora:Z --rm -t antora/antora --cache-dir=./.cache --stacktrace antora-playbook.yml

      - name: Debug build directory
        run: |
          ls -lR build

      - name: Validate build structure
        run: |
          if [ -f "build/index.html" ] && [ -f "build/404.html" ]; then
            echo "Build valid"
          else
            echo "Invalid build structure"
            exit 1
          fi

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: bluebook-build
          path: build/
          retention-days: 1

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: bluebook-build
          path: build/

      - name: Compress build to tarball
        run: |
          tar -czf bluebook-build.tar.gz -C build .

      - name: Upload tarball to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: bluebook-build.tar.gz
          target: /home/gusdur/bluebook-coconut/

      - name: Extract and prepare build on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Extracting tarball"
            rm -rf /home/gusdur/bluebook-coconut/build
            mkdir -p /home/gusdur/bluebook-coconut/build
            tar -xzf /home/gusdur/bluebook-coconut/bluebook-build.tar.gz -C /home/gusdur/bluebook-coconut/build/
            rm /home/gusdur/bluebook-coconut/bluebook-build.tar.gz
            ls -l /home/gusdur/bluebook-coconut/build

      - name: Validate deployment files
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Checking if coconut-draft-inesa.html exists"
            if [ -f "/home/gusdur/bluebook-coconut/build/bluebook/draft/coconut-draft-inesa.html" ]; then
              echo "File exists, continue deployment"
            else
              echo "ERROR: Target HTML not found"
              exit 1
            fi

      - name: Deploy to /var/www/html/build
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Deploying to /var/www/html/build"
            sudo rm -rf /var/www/html/build
            sudo cp -r /home/gusdur/bluebook-coconut/build /var/www/html/build
            sudo chown -R www-data:www-data /var/www/html/build
            sudo chmod -R 755 /var/www/html/build

      - name: Auto-deploy to live directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            echo "Auto-deploying to /var/www/html"
            sudo rm -rf /var/www/html/*
            sudo cp -r /var/www/html/build/* /var/www/html/
            sudo chown -R www-data:www-data /var/www/html
            sudo chmod -R 755 /var/www/html
            echo "Live deploy done"
