name: CI/CD for Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      # Checkout repositori
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup SSH
      - name: Add SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # Test SSH Connection
      - name: Test SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no \
              -p ${{ secrets.VPS_SSH_PORT }} \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} \
              "echo '✅ SSH Connection Successful!'"

      # Build dengan Antora (PATH DIPERBAIKI)
      - name: Build with Antora
        run: |
          echo "Struktur direktori:"
          ls -R
          
          docker run --rm -t \
            -v $PWD:/antora \
            -w /antora \
            antora/antora:3.1.2 \
            --cache-dir=.cache \
            --stacktrace \
            /antora/antora-playbook.yml

      # Verifikasi hasil build
      - name: Verify build output
        run: |
          echo "Isi direktori build:"
          ls -l build/site/
          [ -f build/site/index.html ] || exit 1

      # Deploy ke VPS
      - name: Prepare VPS Directory
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo rm -rf /var/www/html/docs
            sudo mkdir -p /var/www/html/docs

      - name: Upload Documentation
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          source: "build/site/*"
          target: "/var/www/html/docs"
          overwrite: true

      - name: Finalize Deployment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            sudo chown -R www-data:www-data /var/www/html/docs
            sudo chmod -R 755 /var/www/html/docs
            sudo nginx -t && sudo systemctl restart nginx
            echo "🚀 Documentation deployed to: http://${{ secrets.VPS_HOST }}/docs"
